POST http://localhost:3000/api/wilders HTTP/1.1
Content-Type: application/json

{
    "name": "Ben",
    "city": "Villeurbanne",
    "skills":[
        {"title": "javascript", "votes": 5},
        {"title": "express", "votes": 5}
    ]
}

###
GET http://localhost:3000/api/wilders 

###
GET http://localhost:3000/api/wilders/6228e5b01245357f6e89fc31

###
PUT http://localhost:3000/api/wilders/6228e5b01245357f6e89fc31
Content-Type: application/json

{
    "city": "Los Angeles"
}

###
DELETE http://localhost:3000/api/wilders/6228e5b01245357f6e89fc31


